defaults:
  - _self_
  - common
  - logger
  - trainer
  - module
  - data_module
  - callbacks:
    - checkpoint
    - early_stop
    - swa
  - model: base
  - optimizer: adam
  - lr_scheduler: none

# Override
common:
  seed: 42

trainer:
  gpus: 4
  max_epochs: 15
  strategy: dp
  
data_module:
  batch_size: 16

optimizer:
  lr: 1e-4