defaults:
  - _self_
  - common
  - logger
  - trainer
  - module
  - data_module
  - callbacks:
    - checkpoint
    - early_stop
    - swa
  - model: pwcdcnet
  - optimizer: adamw
  - lr_scheduler: step_lr

# Override
common:
  seed: 42

trainer:
  gpus: 4
  max_epochs: 20
  strategy: dp

data_module:
  batch_size: 16

optimizer:
  lr: 1e-5