defaults:
  - _self_
  - common
  - logger
  - trainer
  - module
  - data_module
  - callbacks:
    - checkpoint
    - early_stop
  - model: base
  - optimizer: adamw
  - lr_scheduler: one_cycle_lr

# Override
common:
  seed: 42

trainer:
  gpus: 4
  max_epochs: 20
  strategy: dp
  
data_module:
  batch_size: 16

optimizer:
  lr: 0.0005